version: "3.7"

# This is a composer file intended to run on Docker Swarm
#
# docker build -t vprotest .
# docker network create --driver=overlay app-net
# docker stack deploy app -c app.yml --prune

services:
  frontend:
    image: vprotest:latest
    networks:
      - app-net
    ports:
      - 80:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 10s
  api:
    image: vprotest:latest
    networks:
      - app-net
    ports:
      - 8000:8000
    entrypoint: ["node", "api.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
    deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 10s

  db:
    image: postgres
    networks:
      - app-net
    restart: always
    environment:
      POSTGRES_PASSWORD: simple
      POSTGRES_USER: app
      POSTGRES_DB: app
    volumes:
      - /data/postgresql:/var/lib/postgresql/data

networks:
  app-net:
    external: true
