name: Build and Deploy

on:
  push:
    branches:
    - master
    - dev
    - stage

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set repo name
      run:   echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
      shell: bash

    - name: Set docker image name
      run:   echo ::set-env name=DOCKER_NAME::$(echo docker.pkg.github.com/$GITHUB_REPOSITORY/$REPOSITORY_NAME)
      shell: bash

    - name: Build and Tag
      run: |
        echo $DOCKER_NAME
        docker build --build-arg GIT_SHA=${{github.sha}} -t ${DOCKER_NAME}:${GITHUB_REF##*/} -t ${DOCKER_NAME}:${GITHUB_RUN_NUMBER} . -f Dockerfile

    - name: Push image to Registry
      run: |
        docker image push ${DOCKER_NAME}:${GITHUB_RUN_NUMBER}
        docker image push ${DOCKER_NAME}:${GITHUB_REF##*/}
